<?php
include('../includes/User.php');
include('../includes/PostCategories.php');
session_start();
if (!(isset($_SESSION['user']) && $_SESSION['user']->isAdmin())){
    header('Location: ../login');
}
include('./header.php');

$is_edit = isset($_GET['edit']);
$is_delete = isset($_GET['delete']);

if (isset($_POST['action'])) {
    if ($_POST['action'] == 'update') {
        PostCategories::updateCategory($_POST['cid'], $_POST['cattitle'], $_SESSION['user']->getUID(), $_POST['catslug']);
    }else if($_POST['action'] == 'new'){
        PostCategories::createCategory($_POST['cattitle'], $_SESSION['user']->getUID(), $_POST['catslug'] );
    }
}else if ($is_delete) {
    PostCategories::deleteCategory($_GET['delete']);
}

?>


<div class="container-fluid">
    <div class="row">
        <nav class="col-sm-3 col-md-2 d-none d-sm-block bg-light sidebar">
            <ul class="nav nav-pills flex-column">
                <li class="nav-item">
                    <a class="nav-link" href="./index.php">Overview <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="./createpost.php">Create Post</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="./categories.php">Categories</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="./links.php">Edit Links</a>
                </li>
            </ul>
        </nav>

        <main class="col-sm-9 ml-sm-auto col-md-10 pt-3" role="main">
            <h1>Categories</h1>
            <h2>Create New Category</h2>
            <form method="post" action="./categories.php">
                <div class="form-group">
                    <label for="categoryName">Category Name</label>
                    <input name="cattitle" type="text" class="form-control" id="categoryName" placeholder="Category Name" value="<?=$is_edit ? PostCategories::getCategory($_GET['edit'])->title : "" ?>" required>
                </div>
                <input type="hidden" name="cid" value="<?=$is_edit ? $_GET['edit'] : ""?>">
                <input type="hidden" name="catuid" value="<?=$_SESSION['user']->getUID();?>"/>
                <div class="form-group">
                    <label for="categorySlug">Slug</label>
                    <input name="catslug" type="text" class="form-control" id="categorySlug" placeholder="Slug (Ideally will be autogenerated from category name)" value="<?=$is_edit ? PostCategories::getCategory($_GET['edit'])->slug : "" ?>" required>
                    <small id="categorySlug" class="form-text text-muted">This is the url where the posts will be categorized so a value of 'slug' would be located at kylepeeler.io/blog/categories/slug.</small>

                </div>
                <button type="submit" class="btn btn-primary" name="action" value="<?=$is_edit ? "update" : "new"?>">Submit</button>
            </form>
            <br/>
            <br/>
            <h2>Categories</h2>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Category ID#</th>
                        <th>Category Title</th>
                        <th>Category Slug</th>
                        <th>Edit Category</th>
                        <th>Delete Category</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    PostCategories::displayCategories();
                    ?>
                    </tbody>
                </table>
            </div>
        </main>
    </div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
</body>
</html>